name: speed
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.2.0
  #animacion de cargando
  flutter_spinkit: ^5.0.0
  flutter_statusbar_manager: ^2.0.0
  flutter_svg: ^0.22.0
  get: ^4.1.4
  get_storage: ^2.0.2
  shared_preferences: ^2.0.5
  firebase_auth: ^1.2.0
  #firebase_auth: ^0.20.1
  cloud_firestore: ^2.2.0
  #cloud_firestore: ^0.16.0
  firebase_core: ^1.2.0
  #firebase_core: ^0.7.0
  # firebase_messaging: ^10.0.0
  progress_dialog: ^1.2.4
  # google_maps_flutter: ^2.0.6
  google_maps_flutter: ^2.0.6
  # flutter_google_places: ^0.2.6
  # flutter_google_places: ^0.2.7
  google_place: ^0.4.0
  geolocator: ^7.0.3
  # geolocator: ^6.1.13
  location: ^4.2.1
  # location: ^3.1.0
  # enviar posicion del taxi en TR y ubicacion de puntos a rango especifico
  geoflutterfire: ^3.0.1
  # geocoder: ^0.2.1
  # geocoding: ^1.0.5
  geocoder: ^0.2.1
  geocoding: ^2.0.0
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.0
  lottie: ^1.1.0
  firebase_messaging: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_styles/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
        - asset: assets/fonts/Rubik.ttf
        - asset: assets/fonts/RubikI.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
